hspeed = random(8)-4;
vspeed = -random(4)-2;
gravity = 0.25;
image_speed = 0;
image_xscale = 2;
image_yscale = 2;
var zx = instance_create_depth(0,0,0,view_an2);
zx.asdf = 8;
audio_play_sound(snd02_2, 0, false, world.sound_vol);
ab = 1;