if (!player.Gravity or player.GravityH) {
    player.Gravity = true;
    player.GravityH = false;
    audio_play_sound(sndVJump, 0, false);
}
if (room != Stage02K and room != Stage04G) world.warn = 0;
with(player) io_clear();
switch(room) {
    case Stage01A: room_goto(Stage01B);
                    player.x = 32;
                    player.y = 64;
                    break;
    case Stage01B: room_goto(Stage01C);
                    player.x = 96;
                    player.y = 512;
                    break;
    case Stage01C: room_goto(Stage01D);
                    player.x = 32;
                    player.y = 512;
                    break;
    case Stage01D: room_goto(Stage01E);
                    player.x = 64;
                    player.y = 512;
                    break;
    case Stage01E: room_goto(Stage01F);
                    player.x = 768;
                    player.y = 128;
                    break;
    case Stage01F: room_goto(Stage01G);
                    player.x = 32;
                    player.y = 512;
                    break;
    case Stage01G: room_goto(Stage01H);
                    player.x = 16;
                    player.y = 64;
                    break;
    case Stage01H: if y < 608 {
                    room_goto(Stage01I);
                    player.x = 64;
                    player.y = 64;
                   } else {
                    
                   }
                    break;
    case Stage01I: room_goto(Stage01J);
                    player.x = 48;
                    player.y = 2752;
                    break;
    case Stage01J: room_goto(Stage01Bs);
                    player.x = 64;
                    player.y = 384;
                    world.achieve[13] = 1;
                    break;
    case Stage02A: room_goto(Stage02B);
                    player.x = 32;
                    player.y = 64;
                    break;
    case Stage02B: room_goto(Stage02C);
                    player.x = 864;
                    player.y = 64;
                    break;
    case Stage02C: room_goto(Stage02D);
                    player.x = 768;
                    player.y = 448;
                    break;
    case Stage02D: room_goto(Stage02E);
                    player.x = 48;
                    player.y = 32;
                    break;
    case Stage02E: room_goto(Stage02F);
                    player.x = 64;
                    player.y = 544;
                    break;
    case Stage02F: room_goto(Stage02G);
                    player.x = 64;
                    player.y = 128;
                    break;
    case Stage02G: room_goto(Stage02H);
                    player.x = 32;
                    player.y = 512;
                    break;
    case Stage02H: room_goto(Stage02I);
                    player.x = 32;
                    player.y = 64;
                    break;
    case Stage02I: room_goto(Stage02J);
                    player.x = 16;
                    player.y = 496;
                    break;
    case Stage02J: room_goto(Stage02K);
                    player.x = 320;
                    player.y = 544;
                    break;
    case Stage02K: room_goto(Stage02L);
                    player.x = 128;
                    player.y = 576;
                    break;
    case Stage02L: room_goto(Stage02Sr);
                    player.x = 640;
                    player.y = 464;
                    break;
    case Stage03A: room_goto(Stage03B);
                    player.x = 416;
                    player.y = 416;
                    break;
    case Stage03B: room_goto(Stage03C);
                    player.x = 64;
                    player.y = 544;
                    break;
    case Stage03C: room_goto(Stage03D);
                    player.x = 32;
                    player.y = 288;
                    break;
    case Stage03D: room_goto(Stage03E);
                    player.x = 32;
                    player.y = 480;
                    player.max_hspd = 3;
                    break;
    case Stage03F: room_goto(Stage03G);
                    player.x = 736;
                    player.y = 288;
                    break;
    case Stage03G: room_goto(Stage03H);
                    player.x = 32;
                    player.y = 544;
                    break;
    case Stage03H: room_goto(Stage03I);
                    player.x = 64;
                    player.y = 512;
                    break;
    case Stage03I: room_goto(Stage03J);
                    player.x = 80;
                    player.y = 16;
                    break;
    case Stage03J: if y < 608 {
                    room_goto(Stage03K);
                    player.x = 64;
                    player.y = 64;
                   } else {
                    room_goto(Stage03Sr);
                    player.x = 384;
                    player.y = 512;
                   }
                    break;
    case Stage03K: room_goto(Stage03L);
                    player.x = 19;
                    player.y = 304;
                    break;
    case Stage03L: room_goto(Stage03Bs);
                    player.x = 128;
					player.y = 480;
                    world.achieve[28] = 1;
                    break;
    case Stage04A: room_goto(Stage04B);
                    player.x = 16;
                    player.y = 528;
                    break;
    case Stage04B: room_goto(Stage04C);
                    player.x = 64;
                    player.y = 560;
                    break;
    case Stage04C: room_goto(Stage04D);
                    player.x = 32;
                    player.y = 192;
                    break;
    case Stage04D: room_goto(Stage04E);
                    player.x = 64;
                    player.y = 512;
                    break;
    case Stage04E: room_goto(Stage04F);
                    player.x = 416;
                    player.y = 528;
                    break;
    case Stage04F: room_goto(Stage04G);
                    player.x = 352;
                    player.y = 384;
                    break;
    case Stage04G: room_goto(Stage04H);
                    player.x = 552;
                    player.y = 416;
                    break;
    case Stage04H: room_goto(Stage04I);
                    player.x = 64;
                    player.y = 544;
                    break;
    case Stage04I: room_goto(Stage04J);
                    player.x = 32;
                    player.y = 512;
                    break;
    case Stage04J: room_goto(Stage04K);
                    player.x = 736;
                    player.y = 544;
                    break;
    case Stage04K: room_goto(Stage04L);
                    player.x = 96;
                    player.y = 512;
                    break;
    case Stage04L: room_goto(Stage04M);
                    player.x = 96;
                    player.y = 512;
                    break;
    case Stage04M: room_goto(Stage04Bs);
                    player.x = 400;
                    player.y = 512;
                    world.achieve[36] = 1;
                    break;
    //case someRoom: room_goto(someOtherRoom);
    //               player.x = ##;
    //               player.y = ##;
    //               break;
}